### ISSUE TITLE
Unable to delete previous version

### ISSUE THREAD

**Issue by itsFurty** [JtdeGraaf/IsThereAnyDeal-DeckyPlugin#1]
I'm attempting to update to the latest version. I'm receiving an error when trying to delete the old version's folder. 

"Could not delete file /home/deck/homebrew/plugins/IsThereAnyDeal-DeckyPlugin-main/src/components/PriceComparison.tsx."

I've tried changing the file's permissions but I'm unable to do so. Any help is appreciated.

**Comment by JtdeGraaf** [comment]
Hi, 

have you tried giving the entire folder permissions? For me that works.

**Comment by itsFurty** [comment]
For some reason, the permissions settings are grayed out when trying to change the folder settings. I'm able to change the permissions for every other folder aside from the IsThereAnyDeal folder. It's very strange. I'll have to do some searching to see what I can do. Apologies for taking your time.

**Comment by JtdeGraaf** [comment]
Have you given the parent folder permissions where the IsThereAnyDeal folder is located in? Another solution might be to uninstall it from game mode using decky loader.
