### ISSUE TITLE
Move price display to side menu on store page

### ISSUE THREAD

**Issue by SonOfDiablo** [JtdeGraaf/IsThereAnyDeal-DeckyPlugin#2]
**Is your feature request related to a problem? Please describe.**
The current way the plugin is displaying prices in the footer doesn't work well with the CSSLoader theme called ArtHero (specifically it's Smaller Footer setting) 

**Describe the solution you'd like**
Instead of showing the price in the footer, would it be possible to show it in the right side menu when on a store page? For example under the steam price? 

**Additional context**
A screenshot of the suggested location 
![download (3)~2.jpeg](https://github.com/JtdeGraaf/IsThereAnyDeal-DeckyPlugin/assets/9123250/f273595d-601b-4c18-b2a6-543c35ec3a92)

**Comment by JtdeGraaf** [comment]
This would indeed be preferable, but sadly it is near impossible to alter the store UI itself because the UI is not part of the Steam Deck's UI. It is actually just an embedded webpage.

**Comment by JtdeGraaf** [comment]
But as a workaround I could implement a setting to alter the font size.

**Comment by SonOfDiablo** [comment]
> This would indeed be preferable, but sadly it is near impossible to alter the store UI itself because the UI is not part of the Steam Deck's UI. It is actually just an embedded webpage.

Oh that really sucks...




> But as a workaround I could implement a setting to alter the font size.

That would be great! 
I would really like to use this plugin, but I would hate to mess up the theme I got going for my Deck at the moment.
So will really appreciate it if this was possible :)

**Comment by JtdeGraaf** [comment]
The workaround will ship in the next update, probably next week or something
