### ISSUE TITLE
Enormous log files.

### ISSUE THREAD

**Issue by Neubulae** [JtdeGraaf/IsThereAnyDeal-DeckyPlugin#8]
**Describe the bug**
I've found a few gigantic log files under the directory, I wonder what happened.

**To Reproduce**
I have no idea since the files are literally Gigabytes in size, but after some investigation I see the files are clearly spammed with something `Get paddingBottom` of some sort.

**Expected behavior**
The Issue never happened before Sept. 20th.

**Steam version**
Latest Steam Beta, with latest Decky release.

**Comment by JtdeGraaf** [comment]
Well, that's not good.

I suppose this is caused by the Decky 3.0 release, which was released on September 17th. 

I'll take a look at it this weekend, thanks for the report.

**Comment by JtdeGraaf** [comment]
I am unable to reproduce this on the stable version of SteamOS.

I have not tested the beta branch and will not. I'd suggest to move to the stable branch of SteamOS.
